import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import StoreProvider from "~/provides/redux-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <StoreProvider>
          <main className="flex min-h-screen flex-col items-center justify-center bg-white p-2">
            {children}
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
